name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: dummy_variable
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Run tests
        id: run-tests
        run: >
          poetry run pytest \
            --junitxml=pytest.xml \
            --cov-report=term-missing:skip-covered \
            --cov-report=xml:coverage.xml \
            --cov=src tests
      - name: Upload pytest junitxml artifacts.
        uses: actions/upload-artifact@v2
        with:
          name: pytest-junitxml
          path: pytest.xml

  coverage:
    runs-on: ubuntu-latest
    needs: unit
    if: success() || failure()
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Get pytest junitxml artifacts
        uses: actions/download-artifact@v2
        with:
          name: pytest-junitxml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: poetry
      - run: |
          poetry install
          poetry run mypy .

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isort/isort-action@v1
        with:
          configuration: --profile black
